// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    name: 'Cumpleaños Mascota',
    subject: 'Hoy es el cumpleaños de Lucky, no te olvides darle una sorpresa!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Día Festivo',
    subject: 'Hoy es el navidad, no te olvides darle una sorpresa a tus clientes!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Aniversario Cliente',
    subject: 'Hoy es el aniversario de María número 5 como cliente, no te olvides darle una sorpresa!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Aniversario GPF',
    subject: 'Hoy es un día muy especial, no te olvides te compartir tú alegría con tus clientes!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Ausencia Empleado',
    subject: 'Juan se va a ausentar una semana, no te sobrecargues con trabajo!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Entrega Pedido',
    subject: "Que no se te olvide el pedido de Kevin, es un Lolita's Buffalo and Beef",
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Cumpleaños Mascota',
    subject: 'Hoy es el cumpleaños de Lucky, no te olvides darle una sorpresa!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Día Festivo',
    subject: 'Hoy es el navidad, no te olvides darle una sorpresa a tus clientes!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Aniversario Cliente',
    subject: 'Hoy es el aniversario de María número 5 como cliente, no te olvides darle una sorpresa!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Aniversario GPF',
    subject: 'Hoy es un día muy especial, no te olvides te compartir tú alegría con tus clientes!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Ausencia Empleado',
    subject: 'Juan se va a ausentar una semana, no te sobrecargues con trabajo!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Entrega Pedido',
    subject: "Que no se te olvide el pedido de Kevin, es un Lolita's Buffalo and Beef",
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Cumpleaños Mascota',
    subject: 'Hoy es el cumpleaños de Lucky, no te olvides darle una sorpresa!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Día Festivo',
    subject: 'Hoy es el navidad, no te olvides darle una sorpresa a tus clientes!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Aniversario Cliente',
    subject: 'Hoy es el aniversario de María número 5 como cliente, no te olvides darle una sorpresa!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Aniversario GPF',
    subject: 'Hoy es un día muy especial, no te olvides te compartir tú alegría con tus clientes!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Ausencia Empleado',
    subject: 'Juan se va a ausentar una semana, no te sobrecargues con trabajo!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Entrega Pedido',
    subject: "Que no se te olvide el pedido de Kevin, es un Lolita's Buffalo and Beef",
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Cumpleaños Mascota',
    subject: 'Hoy es el cumpleaños de Lucky, no te olvides darle una sorpresa!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Día Festivo',
    subject: 'Hoy es el navidad, no te olvides darle una sorpresa a tus clientes!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Aniversario Cliente',
    subject: 'Hoy es el aniversario de María número 5 como cliente, no te olvides darle una sorpresa!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Aniversario GPF',
    subject: 'Hoy es un día muy especial, no te olvides te compartir tú alegría con tus clientes!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Ausencia Empleado',
    subject: 'Juan se va a ausentar una semana, no te sobrecargues con trabajo!',
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'Entrega Pedido',
    subject: "Que no se te olvide el pedido de Kevin, es un Lolita's Buffalo and Beef",
    preview: 'Esto es un texto de prueba no te lo tomes tan personal, es para probar el tamaño total de la tabla',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
];
